// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneDirectory.Server;

#nullable disable

namespace PhoneDirectory.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("DepartmentEmployee", b =>
                {
                    b.Property<int>("DepartmentsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DepartmentsId", "EmployeesId");

                    b.HasIndex("EmployeesId");

                    b.ToTable("DepartmentEmployee");

                    b.HasData(
                        new
                        {
                            DepartmentsId = 1,
                            EmployeesId = 1
                        },
                        new
                        {
                            DepartmentsId = 2,
                            EmployeesId = 2
                        },
                        new
                        {
                            DepartmentsId = 3,
                            EmployeesId = 3
                        },
                        new
                        {
                            DepartmentsId = 4,
                            EmployeesId = 4
                        },
                        new
                        {
                            DepartmentsId = 5,
                            EmployeesId = 5
                        },
                        new
                        {
                            DepartmentsId = 1,
                            EmployeesId = 6
                        },
                        new
                        {
                            DepartmentsId = 2,
                            EmployeesId = 7
                        },
                        new
                        {
                            DepartmentsId = 3,
                            EmployeesId = 8
                        },
                        new
                        {
                            DepartmentsId = 4,
                            EmployeesId = 9
                        },
                        new
                        {
                            DepartmentsId = 5,
                            EmployeesId = 10
                        },
                        new
                        {
                            DepartmentsId = 1,
                            EmployeesId = 11
                        },
                        new
                        {
                            DepartmentsId = 2,
                            EmployeesId = 12
                        },
                        new
                        {
                            DepartmentsId = 3,
                            EmployeesId = 13
                        },
                        new
                        {
                            DepartmentsId = 4,
                            EmployeesId = 14
                        },
                        new
                        {
                            DepartmentsId = 5,
                            EmployeesId = 15
                        },
                        new
                        {
                            DepartmentsId = 1,
                            EmployeesId = 16
                        },
                        new
                        {
                            DepartmentsId = 2,
                            EmployeesId = 17
                        },
                        new
                        {
                            DepartmentsId = 3,
                            EmployeesId = 18
                        },
                        new
                        {
                            DepartmentsId = 4,
                            EmployeesId = 19
                        },
                        new
                        {
                            DepartmentsId = 5,
                            EmployeesId = 20
                        },
                        new
                        {
                            DepartmentsId = 1,
                            EmployeesId = 21
                        },
                        new
                        {
                            DepartmentsId = 2,
                            EmployeesId = 22
                        },
                        new
                        {
                            DepartmentsId = 3,
                            EmployeesId = 23
                        },
                        new
                        {
                            DepartmentsId = 4,
                            EmployeesId = 24
                        },
                        new
                        {
                            DepartmentsId = 5,
                            EmployeesId = 25
                        },
                        new
                        {
                            DepartmentsId = 1,
                            EmployeesId = 26
                        },
                        new
                        {
                            DepartmentsId = 2,
                            EmployeesId = 27
                        },
                        new
                        {
                            DepartmentsId = 3,
                            EmployeesId = 28
                        },
                        new
                        {
                            DepartmentsId = 4,
                            EmployeesId = 29
                        },
                        new
                        {
                            DepartmentsId = 5,
                            EmployeesId = 30
                        },
                        new
                        {
                            DepartmentsId = 1,
                            EmployeesId = 31
                        },
                        new
                        {
                            DepartmentsId = 2,
                            EmployeesId = 32
                        },
                        new
                        {
                            DepartmentsId = 3,
                            EmployeesId = 33
                        },
                        new
                        {
                            DepartmentsId = 4,
                            EmployeesId = 34
                        },
                        new
                        {
                            DepartmentsId = 5,
                            EmployeesId = 35
                        });
                });

            modelBuilder.Entity("PhoneDirectory.Shared.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DepartmentLeadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Executive"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = 4,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Maintenance"
                        });
                });

            modelBuilder.Entity("PhoneDirectory.Shared.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeTypeId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Extension")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone2")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeTypeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "atalat@acme.com",
                            EmployeeTypeId = 1,
                            Extension = 10,
                            FirstName = "Arif",
                            LastName = "Talat",
                            Phone1 = "951-555-1210",
                            Phone2 = "213-555-1001"
                        },
                        new
                        {
                            Id = 2,
                            Email = "acaryn@acme.com",
                            EmployeeTypeId = 1,
                            Extension = 11,
                            FirstName = "Aileas",
                            LastName = "Caryn",
                            Phone1 = "951-555-1211",
                            Phone2 = "213-555-1002"
                        },
                        new
                        {
                            Id = 3,
                            Email = "afatma@acme.com",
                            EmployeeTypeId = 1,
                            Extension = 12,
                            FirstName = "Ajay",
                            LastName = "Fatma",
                            Phone1 = "951-555-1212",
                            Phone2 = "213-555-1003"
                        },
                        new
                        {
                            Id = 4,
                            Email = "jadsila@acme.com",
                            EmployeeTypeId = 1,
                            Extension = 13,
                            FirstName = "Jacira",
                            LastName = "Adsila",
                            Phone1 = "951-555-1213",
                            Phone2 = "213-555-1004"
                        },
                        new
                        {
                            Id = 5,
                            Email = "aumukoro@acme.com",
                            EmployeeTypeId = 1,
                            Extension = 14,
                            FirstName = "Alister",
                            LastName = "Umukoro",
                            Phone1 = "951-555-1214",
                            Phone2 = "213-555-1005"
                        },
                        new
                        {
                            Id = 6,
                            Email = "mfitzgerald@acme.com",
                            EmployeeTypeId = 2,
                            Extension = 15,
                            FirstName = "Malaika",
                            LastName = "Fitzgerald",
                            Phone1 = "951-555-1215",
                            Phone2 = "213-555-1006"
                        },
                        new
                        {
                            Id = 7,
                            Email = "cgregory@acme.com",
                            EmployeeTypeId = 2,
                            Extension = 16,
                            FirstName = "Charleigh",
                            LastName = "Gregory",
                            Phone1 = "951-555-1216",
                            Phone2 = "213-555-1007"
                        },
                        new
                        {
                            Id = 8,
                            Email = "aingram@acme.com",
                            EmployeeTypeId = 2,
                            Extension = 17,
                            FirstName = "Anais ",
                            LastName = "Ingram",
                            Phone1 = "951-555-1217",
                            Phone2 = "213-555-1008"
                        },
                        new
                        {
                            Id = 9,
                            Email = "bbruce@acme.com",
                            EmployeeTypeId = 2,
                            Extension = 18,
                            FirstName = "Blane",
                            LastName = "Bruce",
                            Phone1 = "951-555-1218",
                            Phone2 = "213-555-1009"
                        },
                        new
                        {
                            Id = 10,
                            Email = "evasquez@acme.com",
                            EmployeeTypeId = 2,
                            Extension = 19,
                            FirstName = "Elli",
                            LastName = "Vasquez",
                            Phone1 = "951-555-1219",
                            Phone2 = "213-555-1010"
                        },
                        new
                        {
                            Id = 11,
                            Email = "eschroeder@acme.com",
                            EmployeeTypeId = 3,
                            Extension = 20,
                            FirstName = "Efan",
                            LastName = "Schroeder",
                            Phone1 = "951-555-1220",
                            Phone2 = "213-555-1011"
                        },
                        new
                        {
                            Id = 12,
                            Email = "kedwards@acme.com",
                            EmployeeTypeId = 3,
                            Extension = 21,
                            FirstName = "Kelsea",
                            LastName = "Edwards",
                            Phone1 = "951-555-1221",
                            Phone2 = "213-555-1012"
                        },
                        new
                        {
                            Id = 13,
                            Email = "kmcneill@acme.com",
                            EmployeeTypeId = 3,
                            Extension = 22,
                            FirstName = "Kaja ",
                            LastName = "Mcneill",
                            Phone1 = "951-555-1222",
                            Phone2 = "213-555-1013"
                        },
                        new
                        {
                            Id = 14,
                            Email = "cnewton@acme.com",
                            EmployeeTypeId = 3,
                            Extension = 23,
                            FirstName = "Cherise",
                            LastName = "Newton",
                            Phone1 = "951-555-1223",
                            Phone2 = "213-555-1014"
                        },
                        new
                        {
                            Id = 15,
                            Email = "mburton@acme.com",
                            EmployeeTypeId = 3,
                            Extension = 24,
                            FirstName = "Maud",
                            LastName = "Burton",
                            Phone1 = "951-555-1224",
                            Phone2 = "213-555-1015"
                        },
                        new
                        {
                            Id = 16,
                            Email = "shutton@acme.com",
                            EmployeeTypeId = 4,
                            Extension = 25,
                            FirstName = "Sheridan",
                            LastName = "Hutton",
                            Phone1 = "951-555-1225",
                            Phone2 = "213-555-1016"
                        },
                        new
                        {
                            Id = 17,
                            Email = "cfleming@acme.com",
                            EmployeeTypeId = 4,
                            Extension = 26,
                            FirstName = "Cassandra",
                            LastName = "Fleming",
                            Phone1 = "951-555-1226",
                            Phone2 = "213-555-1017"
                        },
                        new
                        {
                            Id = 18,
                            Email = "mandrew@acme.com",
                            EmployeeTypeId = 4,
                            Extension = 27,
                            FirstName = "Maariyah",
                            LastName = "Andrew",
                            Phone1 = "951-555-1227",
                            Phone2 = "213-555-1018"
                        },
                        new
                        {
                            Id = 19,
                            Email = "mmejia@acme.com",
                            EmployeeTypeId = 4,
                            Extension = 28,
                            FirstName = "Nathaniel",
                            LastName = "Mejia",
                            Phone1 = "951-555-1228",
                            Phone2 = "213-555-1019"
                        },
                        new
                        {
                            Id = 20,
                            Email = "hboone@acme.com",
                            EmployeeTypeId = 4,
                            Extension = 29,
                            FirstName = "Hawa",
                            LastName = "Boone",
                            Phone1 = "951-555-1229",
                            Phone2 = "213-555-1020"
                        },
                        new
                        {
                            Id = 21,
                            Email = "thamilton@acme.com",
                            EmployeeTypeId = 5,
                            Extension = 30,
                            FirstName = "Tahmid",
                            LastName = "Hamilton",
                            Phone1 = "951-555-1230",
                            Phone2 = "213-555-1021"
                        },
                        new
                        {
                            Id = 22,
                            Email = "rkent@acme.com",
                            EmployeeTypeId = 5,
                            Extension = 31,
                            FirstName = "Raiden",
                            LastName = "Kent",
                            Phone1 = "951-555-1231",
                            Phone2 = "213-555-1022"
                        },
                        new
                        {
                            Id = 23,
                            Email = "rallison@acme.com",
                            EmployeeTypeId = 5,
                            Extension = 32,
                            FirstName = "Rania",
                            LastName = "Allison",
                            Phone1 = "951-555-1232",
                            Phone2 = "213-555-1023"
                        },
                        new
                        {
                            Id = 24,
                            Email = "dmcnamara@acme.com",
                            EmployeeTypeId = 5,
                            Extension = 33,
                            FirstName = "Dotty",
                            LastName = "Mcnamara",
                            Phone1 = "951-555-1233",
                            Phone2 = "213-555-1024"
                        },
                        new
                        {
                            Id = 25,
                            Email = "hburris@acme.com",
                            EmployeeTypeId = 5,
                            Extension = 34,
                            FirstName = "Helen",
                            LastName = "Burris",
                            Phone1 = "951-555-1234",
                            Phone2 = "213-555-1025"
                        },
                        new
                        {
                            Id = 26,
                            Email = "ljenkins@acme.com",
                            EmployeeTypeId = 6,
                            Extension = 35,
                            FirstName = "Lilah",
                            LastName = "Jenkins",
                            Phone1 = "951-555-1235",
                            Phone2 = "213-555-1026"
                        },
                        new
                        {
                            Id = 27,
                            Email = "amccullough@acme.com",
                            EmployeeTypeId = 6,
                            Extension = 36,
                            FirstName = "Ajay",
                            LastName = "Mccullough",
                            Phone1 = "951-555-1236",
                            Phone2 = "213-555-1027"
                        },
                        new
                        {
                            Id = 28,
                            Email = "jgolden@acme.com",
                            EmployeeTypeId = 6,
                            Extension = 37,
                            FirstName = "Joss",
                            LastName = "Golden",
                            Phone1 = "951-555-1237",
                            Phone2 = "213-555-1028"
                        },
                        new
                        {
                            Id = 29,
                            Email = "fhoughton@acme.com",
                            EmployeeTypeId = 6,
                            Extension = 38,
                            FirstName = "Franklin",
                            LastName = "Houghton",
                            Phone1 = "951-555-1238",
                            Phone2 = "213-555-1029"
                        },
                        new
                        {
                            Id = 30,
                            Email = "owilcox@acme.com",
                            EmployeeTypeId = 6,
                            Extension = 39,
                            FirstName = "Oscar",
                            LastName = "Wilcox",
                            Phone1 = "951-555-1239",
                            Phone2 = "213-555-1030"
                        },
                        new
                        {
                            Id = 31,
                            Email = "mhoughton@acme.com",
                            EmployeeTypeId = 7,
                            Extension = 40,
                            FirstName = "Martyna",
                            LastName = "Houghton",
                            Phone1 = "951-555-1240",
                            Phone2 = "213-555-1031"
                        },
                        new
                        {
                            Id = 32,
                            Email = "ppugh@acme.com",
                            EmployeeTypeId = 7,
                            Extension = 41,
                            FirstName = "Prince",
                            LastName = "Pugh",
                            Phone1 = "951-555-1241",
                            Phone2 = "213-555-1032"
                        },
                        new
                        {
                            Id = 33,
                            Email = "ibull@acme.com",
                            EmployeeTypeId = 7,
                            Extension = 42,
                            FirstName = "Irene",
                            LastName = "Bull",
                            Phone1 = "951-555-1242",
                            Phone2 = "213-555-1033"
                        },
                        new
                        {
                            Id = 34,
                            Email = "hmcneil@acme.com",
                            EmployeeTypeId = 7,
                            Extension = 43,
                            FirstName = "Herbert",
                            LastName = "Mcneil",
                            Phone1 = "951-555-1243",
                            Phone2 = "213-555-1034"
                        },
                        new
                        {
                            Id = 35,
                            Email = "bhuber@acme.com",
                            EmployeeTypeId = 7,
                            Extension = 44,
                            FirstName = "Benjamin",
                            LastName = "Huber",
                            Phone1 = "951-555-1244",
                            Phone2 = "213-555-1035"
                        });
                });

            modelBuilder.Entity("PhoneDirectory.Shared.Entities.EmployeeType", b =>
                {
                    b.Property<int>("EmployeeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeTypeId");

                    b.ToTable("EmployeeTypes");

                    b.HasData(
                        new
                        {
                            EmployeeTypeId = 1,
                            DisplayOrder = 1,
                            Title = "Vice_President"
                        },
                        new
                        {
                            EmployeeTypeId = 2,
                            DisplayOrder = 2,
                            Title = "Director"
                        },
                        new
                        {
                            EmployeeTypeId = 3,
                            DisplayOrder = 3,
                            Title = "Assistant_Director"
                        },
                        new
                        {
                            EmployeeTypeId = 4,
                            DisplayOrder = 4,
                            Title = "Manager"
                        },
                        new
                        {
                            EmployeeTypeId = 5,
                            DisplayOrder = 5,
                            Title = "Assistant_Manager"
                        },
                        new
                        {
                            EmployeeTypeId = 6,
                            DisplayOrder = 6,
                            Title = "Supervisor"
                        },
                        new
                        {
                            EmployeeTypeId = 7,
                            DisplayOrder = 7,
                            Title = "Employee"
                        });
                });

            modelBuilder.Entity("DepartmentEmployee", b =>
                {
                    b.HasOne("PhoneDirectory.Shared.Entities.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoneDirectory.Shared.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoneDirectory.Shared.Entities.Employee", b =>
                {
                    b.HasOne("PhoneDirectory.Shared.Entities.EmployeeType", "EmployeeType")
                        .WithMany("Employee")
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("PhoneDirectory.Shared.Entities.EmployeeType", b =>
                {
                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
